version: "2"
services:
  gateway:
    image: caligin/shepherd_gateway
    fip: 209.177.93.196
    links:
       - app:shepherd
    ports:
       - "80:80"
       - "443:443"
  bastion:
    image: caligin/shepherd_bastion
    links:
      - app:shepherd
    ports:
      - "6022:22"
  app:
    image: caligin/shepherd_app
    links:
      - database:database
    ports:
      - 80
  database:
    image: caligin/shepherd_database
    environment:
      - MYSQL_ROOT_PASSWORD=CowSaysMoo
    ports:
      - 3306
